# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: "18.x"

      - name: install tree-sitter
        run: npm install tree-sitter-cli@0.20

      - name: print tree-sitter version
        run: npx tree-sitter --version

      - name: generate the grammar
        run: npx tree-sitter generate

      - name: test
        run: npx tree-sitter test
